name: Build Project

on:
  push:
    branches: [ main ] # 或者你的主分支名称
  pull_request:
    branches: [ main ] # 或者你的主分支名称

jobs:
  build:
    runs-on: ubuntu-latest # 选择你的运行环境

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 # 设置你需要的 JDK 版本
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build # 运行 Gradle 构建命令

    # 可选：上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: project-artifacts
        path: build/libs/
