name: Build and Upload APK

on:
  push:
    branches: [ main ]  # 触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 拉取代码

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'  # 保持原 JDK 版本和分发渠道

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3  # 替换为官方推荐的新动作

    - name: Build with Gradle
      run: ./gradlew assembleRelease  # 用命令行替代 deprecated 的 arguments 参数
      # Windows 环境需改为：gradlew.bat assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: app/build/outputs/apk/release/*.apk  # 注意：若构建 release，路径需对应 release 目录

